/**
 * Flashcards — Q&A decks generated by Haiku, one per topic/section. Pairs with
 * Study Maps (a section's "📇 Cards"). Stored locally. Each card tracks a status:
 * 0 = new, 1 = review (got it wrong / again), 2 = known.
 */
import { apiFetch } from "../../auth/cloudSync.js";

const KEY = "inkling-flashcards-v1";

function uid(p = "c") { return `${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 7)}`; }

export function loadFlashcardSets() {
  try { const r = localStorage.getItem(KEY); const a = r ? JSON.parse(r) : []; return Array.isArray(a) ? a : []; }
  catch { return []; }
}
function saveAll(sets) { try { localStorage.setItem(KEY, JSON.stringify(sets)); return true; } catch { return false; } }

export function getFlashcardSet(id) { return loadFlashcardSets().find((s) => s.id === id) || null; }

export function saveFlashcardSet(set) {
  const sets = loadFlashcardSets();
  const i = sets.findIndex((s) => s.id === set.id);
  if (i >= 0) sets[i] = set; else sets.unshift(set);
  saveAll(sets);
  return set;
}

export function deleteFlashcardSet(id) { saveAll(loadFlashcardSets().filter((s) => s.id !== id)); }

/** An existing set for this map+section, if already generated (avoid duplicates). */
export function findSetFor(mapId, branchId) {
  return loadFlashcardSets().find((s) => s.mapId === mapId && s.branchId === branchId) || null;
}

export function setCardStatus(setId, cardId, status) {
  const set = getFlashcardSet(setId);
  if (!set) return;
  const card = set.cards.find((c) => c.id === cardId);
  if (card) { card.status = status; saveFlashcardSet(set); }
}

export function setProgress(set) {
  const total = set.cards.length;
  const known = set.cards.filter((c) => c.status === 2).length;
  return { total, known, pct: total ? Math.round((known / total) * 100) : 0 };
}

/**
 * Generate a deck via Haiku (server). `meta` ties it to a study map section.
 * @returns {Promise<{ok:boolean, set?:object, reason?:string}>}
 */
export async function generateFlashcards({ topic, section = "", terms = [], mapId = null, branchId = null }) {
  const t = String(topic || "").trim();
  if (t.length < 2) return { ok: false, reason: "empty" };
  let data;
  try {
    data = await apiFetch("/api/inkling/flashcards", {
      method: "POST",
      body: JSON.stringify({ topic: t, section, terms })
    });
  } catch { return { ok: false, reason: "offline" }; }
  if (data?.source === "guest") return { ok: false, reason: "signin" };
  if (data?.source === "capped") return { ok: false, reason: "capped" };
  if (!data?.cards?.length) return { ok: false, reason: "empty" };
  const set = {
    id: uid("set"),
    topic: t,
    section: section || "",
    mapId, branchId,
    createdAt: Date.now(),
    cards: data.cards.map((c) => ({ id: uid("card"), q: c.q, a: c.a, type: c.type || "concept", status: 0 }))
  };
  saveFlashcardSet(set);
  return { ok: true, set };
}
