/**
 * Flashcards — Q&A decks generated by Haiku, one per topic/section. Pairs with
 * Study Maps (a section's "📇 Cards"). Stored locally. Each card tracks a status:
 * 0 = new, 1 = review (got it wrong / again), 2 = known.
 */
import { apiFetch } from "../../auth/cloudSync.js";
import { SEED_DECKS } from "./seedDecks.js";

const KEY = "inkling-flashcards-v1";

function uid(p = "c") { return `${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 7)}`; }

export function loadFlashcardSets() {
  try { const r = localStorage.getItem(KEY); const a = r ? JSON.parse(r) : []; return Array.isArray(a) ? a : []; }
  catch { return []; }
}
function saveAll(sets) { try { localStorage.setItem(KEY, JSON.stringify(sets)); return true; } catch { return false; } }

/**
 * Add any built-in decks that aren't already in the store, so there's always
 * something to study (works offline, no sign-in). Stable ids mean we never
 * duplicate; existing decks (and their progress) are left untouched.
 */
export function ensureSeedDecks() {
  const sets = loadFlashcardSets();
  let changed = false;
  for (const seed of SEED_DECKS) {
    const ver = seed.seedVersion || 1;
    const existing = sets.find((s) => s.id === seed.id);
    if (existing && (existing.seedVersion || 1) >= ver) continue;
    // Carry over per-card status (by stable card id) when refreshing.
    const prevStatus = new Map((existing?.cards || []).map((c) => [c.id, c.status]));
    const deck = {
      id: seed.id,
      seedVersion: ver,
      topic: seed.topic,
      section: seed.section || "",
      mapId: null, branchId: null,
      builtIn: true,
      createdAt: existing?.createdAt || Date.now(),
      cards: seed.cards.map((c) => ({ ...c, type: c.type || "concept", status: prevStatus.get(c.id) || 0 }))
    };
    if (existing) {
      sets[sets.indexOf(existing)] = deck;
    } else {
      sets.unshift(deck);
    }
    changed = true;
  }
  if (changed) saveAll(sets);
  return sets;
}

export function getFlashcardSet(id) { return loadFlashcardSets().find((s) => s.id === id) || null; }

export function saveFlashcardSet(set) {
  const sets = loadFlashcardSets();
  const i = sets.findIndex((s) => s.id === set.id);
  if (i >= 0) sets[i] = set; else sets.unshift(set);
  saveAll(sets);
  return set;
}

export function deleteFlashcardSet(id) { saveAll(loadFlashcardSets().filter((s) => s.id !== id)); }

/** An existing set for this map+section, if already generated (avoid duplicates). */
export function findSetFor(mapId, branchId) {
  return loadFlashcardSets().find((s) => s.mapId === mapId && s.branchId === branchId) || null;
}

export function setCardStatus(setId, cardId, status) {
  const set = getFlashcardSet(setId);
  if (!set) return;
  const card = set.cards.find((c) => c.id === cardId);
  if (card) { card.status = status; saveFlashcardSet(set); }
}

export function setProgress(set) {
  const total = set.cards.length;
  const known = set.cards.filter((c) => c.status === 2).length;
  return { total, known, pct: total ? Math.round((known / total) * 100) : 0 };
}

/**
 * Generate a deck via Haiku (server). `meta` ties it to a study map section.
 * @returns {Promise<{ok:boolean, set?:object, reason?:string}>}
 */
/** Local, no-server recall cards from a branch's subject terms — so "Make cards"
 *  never dead-ends for guests/offline. Sign-in swaps these for AI-written Q&A. */
function localCardsFromTerms(terms = []) {
  const clean = (s) => String(s)
    .replace(/★/g, "")
    .replace(/^\s*(Stage\s*\d+|Throughout)\s*·\s*/i, "")
    .trim();
  const cards = [];
  for (const raw of terms) {
    const label = clean(raw);
    if (label.length < 2) continue;
    cards.push({
      q: `In your own words: what is “${label}”, and why does it matter?`,
      a: "Recall the core idea, then check it against your notes or a resource. Sign in to Inkling to get AI-written answers here.",
      type: "concept"
    });
  }
  return cards;
}

export async function generateFlashcards({ topic, section = "", terms = [], mapId = null, branchId = null }) {
  const t = String(topic || "").trim();
  if (t.length < 2) return { ok: false, reason: "empty" };
  let data = null;
  try {
    data = await apiFetch("/api/inkling/flashcards", {
      method: "POST",
      body: JSON.stringify({ topic: t, section, terms })
    });
  } catch { data = null; }
  // Use the AI cards when the server actually returned some; otherwise fall back
  // to local recall cards so the button always produces a usable set.
  const aiCards = (data && data.source !== "guest" && data.source !== "capped" && Array.isArray(data.cards))
    ? data.cards : [];
  const usedLocal = aiCards.length === 0;
  const rawCards = usedLocal ? localCardsFromTerms(terms) : aiCards;
  if (!rawCards.length) return { ok: false, reason: "empty" };
  const set = {
    id: uid("set"),
    topic: t,
    section: section || "",
    mapId, branchId, local: usedLocal,
    createdAt: Date.now(),
    cards: rawCards.map((c) => ({ id: uid("card"), q: c.q, a: c.a, type: c.type || "concept", status: 0 }))
  };
  saveFlashcardSet(set);
  return { ok: true, set, local: usedLocal };
}
